# Navigation Links

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Historias"
  url = "#historias"
  weight = 20

[[main]]
  name = "Píldoras"
  url = "#pildoras"
  weight = 30

[[main]]
  name = "Publicaciones"
  url = "#publications"
  weight = 40

[[main]]
  name = "Charlas"
  url = "#talks"
  weight = 50

[[main]]
  name = "Experiencia"  # Title of the link.
  url = "experiencia/"  # Widget Page folder name.
  weight = 60  # Position of the link in the navigation bar.
  
  
[[main]]
  name = "Contacto"
  url = "#contact"
  weight = 70

